#!/bin/bash
container_name=$(docker ps -l | awk 'NR==2{print $2}')

if [ "$container_name" != "voiceitmin" ]; then
  echo "****Please run ./build in a separate window before running this script.****"
  exit 1
fi

container_id=$(docker ps -l | awk 'NR==2{print $1}')
docker cp $container_id:/app/dist/voiceit2.min.js ./dist/voiceit2.min.js
docker stop $container_id
cp dist/voiceit2.min.js ../dist/voiceit2.min.js
cp dist/voiceit2.min.js ../node-example/public/js/voiceit2.min.js
cp dist/voiceit2.min.js ../php-example/js/voiceit2.min.js

echo "****Sucess****"
