<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Tests\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/tests'),
    'Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'ReallySimpleJWT\\Helper\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src/Helper'),
    'ReallySimpleJWT\\Exception\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src/Exception'),
    'ReallySimpleJWT\\' => array($vendorDir . '/rbdwllr/reallysimplejwt/src'),
    '' => array($vendorDir . '/nesbot/carbon/src'),
);
